# Generated by Django 3.2 on 2022-05-08 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='User_Details',
            fields=[
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('aadhaar', models.IntegerField(blank=True)),
                ('f_name', models.CharField(blank=True, max_length=25)),
                ('l_name', models.CharField(blank=True, max_length=25)),
                ('address', models.TextField(blank=True, max_length=100)),
                ('phone_no', models.IntegerField(blank=True)),
                ('gender', models.CharField(max_length=1)),
                ('is_doctor', models.BooleanField(default=False)),
                ('is_patient', models.BooleanField(default=False)),
                ('lat', models.FloatField(default=12.9719)),
                ('lng', models.FloatField(default=77.5937)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.user_details')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.user_details')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fieldtypes')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=10)),
                ('schedule', models.CharField(max_length=500)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
            ],
        ),
    ]
