# Generated by Django 3.2 on 2022-05-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220511_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_sos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctor',
            name='license_no',
            field=models.TextField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='min_fee',
            field=models.IntegerField(default=0),
        ),
    ]
