# Generated by Django 3.2 on 2022-05-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220511_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='mrn',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
