# Generated by Django 3.2 on 2022-05-11 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_patient_mrn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='mrn',
            field=models.CharField(blank=True, max_length=25, unique=True),
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.user_details')),
                ('time', models.TextField(blank=True, max_length=100)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.day')),
            ],
        ),
    ]
