# Generated by Django 3.2 on 2022-05-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220511_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='time',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
