# Generated by Django 3.2 on 2022-05-12 20:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20220513_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='auto_increment_id',
            field=models.AutoField (auto_created = True,
                  primary_key = True,
                  serialize = False, 
                  verbose_name ='ID'
                ),
           
        ),
        migrations.AlterField(
            model_name='slot',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.user_details'),
        ),
    ]
