# Generated by Django 3.2 on 2022-05-12 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20220513_0143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='id',
            new_name='s_id',
        ),
    ]
