# Generated by Django 3.2 on 2022-05-12 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_id_slot_s_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='s_id',
            new_name='id',
        ),
    ]
