# Generated by Django 3.2 on 2022-05-12 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_slot_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user_details'),
        ),
    ]
