# Generated by Django 3.2 on 2022-05-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_slot_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='yoe',
            field=models.IntegerField(default=0),
        ),
    ]
