# Generated by Django 3.2 on 2022-05-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_doctor_yoe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='aadhaar',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='phone_no',
            field=models.IntegerField(blank=True, unique=True),
        ),
    ]
