# Generated by Django 3.2 on 2022-05-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20220513_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('msg', models.TextField(max_length=300)),
                ('name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
    ]
